# Generated by Django 5.2.5 on 2026-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_miles', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('total_driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('route', models.JSONField(blank=True, default=dict)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('day_logs', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
